name: "Add Resource"
description: "Propose adding a resource link"
labels: ["resource"]
body:
  - type: input
    id: section
    attributes:
      label: Section (e.g., 'RAG', 'Agents')
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note (one line)
