name: repo-ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
      - name: Link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --exclude-mail --accept 200..299,403 "**/*.md"
      - name: Build logs index
        run: python3 scripts/build_index.py
